services:
  - type: web
    name: edupal-server
    env: node
    plan: free
    region: oregon
    rootDir: server
    nodeVersion: 22.21.1
    buildCommand: npm install && npm run build && npm run migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
